#!/usr/bin/with-contenv bash

. /opt/gameserver/scripts/l4d2_campaign/env.sh

# 服务器名称
echo "Set server name to $L4D2_SERVER_NAME"
echo "$L4D2_SERVER_NAME" >/app/l4d2/left4dead2/addons/sourcemod/configs/servername.cfg
